# Generated by Django 6.0.5 on 2026-07-16 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alert_type', models.CharField(choices=[('high-temp', 'High Temp'), ('high-humidity', 'High Humidity'), ('low-light', 'Low Light')], max_length=32)),
                ('title', models.CharField(max_length=120)),
                ('description', models.CharField(max_length=240)),
                ('color', models.CharField(default='#ef5350', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('light_on', models.BooleanField(default=True)),
                ('fan_on', models.BooleanField(default=True)),
                ('fan_speed', models.PositiveSmallIntegerField(default=65)),
                ('auto_mode', models.BooleanField(default=True)),
                ('energy_kwh', models.FloatField(default=1.25)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Device State',
            },
        ),
        migrations.CreateModel(
            name='SensorReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temperature', models.FloatField(default=0)),
                ('humidity', models.FloatField(default=0)),
                ('ldr', models.IntegerField(default=0)),
                ('fan_speed', models.PositiveSmallIntegerField(default=0)),
                ('signal', models.PositiveSmallIntegerField(default=0)),
                ('uptime_ms', models.BigIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
