# Generated by Django 4.2.11 on 2026-07-31 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='devicestate',
            name='energy_kwh',
        ),
    ]
