# Generated by Django 5.2.17 on 2026-09-18 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_devicestate_energy_kwh'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicestate',
            name='humidity_alert',
            field=models.PositiveSmallIntegerField(default=60),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='light_on_lux',
            field=models.PositiveSmallIntegerField(default=200),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='temp_full',
            field=models.FloatField(default=40),
        ),
        migrations.AddField(
            model_name='devicestate',
            name='temp_on',
            field=models.FloatField(default=30),
        ),
    ]
